hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6a9ca5c65d6ba60d1a9e5c8c3d9607fd70a6912dabe8f99cc74de4233d68108f"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "bdaedb87300594cb776756286d7f615cba17a460e2b1e63de9f6881f44cb277e"
metafile = true

[[files]]
file = "mods/bibliocraft-legacy.pw.toml"
hash = "e6161f5181a727a4f55cb63fed3036dfa89c6ee5aa4686c3e83c84d436e9efe3"
metafile = true

[[files]]
file = "mods/bovines-and-buttercups.pw.toml"
hash = "a6ed93c1c6bc43e9b58249e7e494aca4cad37b912676d7d414d5f8e911f006b6"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "14ab2481c3c596327425d03444b88426edca8d05f163be0cbd10e5d4868d57ff"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "ec00fdd4f05b8eb824821f4ee77e3a7112d495e7494d90c95fa2b1388a421e1d"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "5301d77d875d6e88c77b5847ada05faefb9376add7366b6fc6c51b4d9dfeefc4"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "f1976746fa3ec72fa97dc8906feb6377646e2145256448fce4b1fe2a1cf56f5e"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "88c81cadf6b02adfe3800604fd49bcb3789045cbcde29b6c82d7231d02095a6e"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "e8416a11187cf969901f67cf992873c0369d1c8546051aa1df934c5974201520"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "6a5503f90eda6b64b4eb121e3b2fb40d33ec8a97abae5dc9db49d37d45200ccf"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d66d60e04febf9160994926cdf55e6f8916b8d4ec6956f047493e8a043f9fdeb"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "2467c6382fe14f9e16195d4ebd88b6570d42b2f18f0f28d3a1c8618e5176b7de"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "93794a68c7b365ebe9d5f672a041a1e99b6d8157e79666a3cfaeec6d790e352a"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "750c6520ea021aae29318d3e4e374e41aa42e624c3c7f91d44d81f6dd2a2cca1"
metafile = true

[[files]]
file = "mods/item-descriptions.pw.toml"
hash = "f7a1b98029664a8ed26cb561012954d8701ea5e67a13769486b3a56d93aa6da4"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "847a77db8396c9b2ff1296e84e55356b66440c2378fc225b15bf5ee277950db4"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "9bc7dc4c926dc2b3b4da09b92e18ccf2b97bec000681a2fe89bb51ec5c8b49e3"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "b6f45ab8987de57f8505a92a608cf2e0945510ba69edbc3836635b1dad874bcd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "c45af825eb134dd15b18c9f0b94c05e54cea8353734222f2dbaa5531a62d55a1"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "c048b0197abcb760736b850404ddb066702eeb8552b12b341d017b7df12c8ba8"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "e2c4195764e4d42bd8535cf28e29c477c40dbec31d45602d1ae748dad50eb7ba"
metafile = true

[[files]]
file = "mods/pyrite.pw.toml"
hash = "1abd095c85ceac3cc328ecc5ac181dabed125052c0d3a5a078a0702c4f69f968"
metafile = true

[[files]]
file = "mods/rapscallions-and-rockhoppers.pw.toml"
hash = "561b9b8407956d2c3e35b590087e9335951bb41c4b8655b6bed5b3c922b2c054"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "d99b63230eb3c56d8b4389e3f5c8c80a2e1927e650d9c46951769f4951e506bd"
metafile = true

[[files]]
file = "mods/useful-spyglass.pw.toml"
hash = "764adbbe74c387d40badad1834d5ccb83d2795da7606542a6c04f7583e52f448"
metafile = true
