hash-format = "sha256"

[[files]]
file = "config/fabrication/block_logo.ini"
hash = "1a58d3ffaaf266eb0f6f3574f15559689fa237be980a13b741834d640d9a8375"

[[files]]
file = "config/fabrication/block_logo.png"
hash = "f2938cfb35d857049425b51f59ce557dd8f329e6b76bef68ffb561f118a4def0"

[[files]]
file = "config/fabrication/classic_block_drops.ini"
hash = "45e501b8528ef8d27c2a67efd27304c81cd0503f8b0671094e6653eefd394b12"

[[files]]
file = "config/fabrication/dimensional_tools.ini"
hash = "14eb4e8cd105c580403c4e5bc6bba831c81aedcf4e6e04485c74e9d3f253689f"

[[files]]
file = "config/fabrication/features.ini"
hash = "da2f9c00a0b5f257dc639410dff7b818fbbe76082e29bde58a4eabdbddd0edc9"

[[files]]
file = "config/fabrication/fscript.ini"
hash = "06d742af1c186bd89bb808f7ff407865f1c08b1ebf7bb2e52ae2d042b64acd16"

[[files]]
file = "config/fabrication/gear_components.ini"
hash = "5a9291467f9f7918687a0d138a61e396cb9299b0b4ea2e4cf4f4d6f3594f865b"

[[files]]
file = "config/fabrication/item_despawn.ini"
hash = "24b26ac0b8ff13889b6b3b00b2309366eb72c36014a9679a82f4cbff46c275f4"

[[files]]
file = "config/fabrication/taggable_players.ini"
hash = "fe069b4316f910f2f3b703cedd9930b73eed74c2ae86909f8b43a8ffd3d1af45"

[[files]]
file = "config/fabrication/yeet_recipes.ini"
hash = "939cfc95ed4a7480ac08d3f692538a348af72c6db693349c61f93f926976d1f2"

[[files]]
file = "mods/advancements-reloaded.pw.toml"
hash = "3b8da4468f2109ea49d43317aa11f9cf9c1408adaca30d76a70dff3a6385c43b"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "015053563a1d8ef3334560cd27f8e832935a26a96f151f059f814092b8db50a2"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "71385a965a8391b709fc68784d7c7933eb837048cf0649d3a20a065258fe3e8c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/audaki-cart-engine.pw.toml"
hash = "b0e24748243ebef6cf35d7f4c523e002693da0697cf94897d6b1a72fcd160b2c"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "bdaedb87300594cb776756286d7f615cba17a460e2b1e63de9f6881f44cb277e"
metafile = true

[[files]]
file = "mods/bedrockify.pw.toml"
hash = "ac5b35d1cd0b1039dbc3a4c1070a6dd17b5c352a7d133e22463b67c47e273617"
metafile = true

[[files]]
file = "mods/bovines-and-buttercups.pw.toml"
hash = "16321a199f9e074555f8550b7dcbc81711fde5422982abd084c87e0898314621"
metafile = true

[[files]]
file = "mods/breakerplacer.pw.toml"
hash = "a4695100ca0d6525dca30f4cbea5c0e6744f76d6ac8009124f6fa96ad091dd19"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "8f6036f3067befffc33b106df2e56fc076deaeffecf079957c46c6c00def2ed1"
metafile = true

[[files]]
file = "mods/bundled_.pw.toml"
hash = "0ab032a5ecd0385858fe53ea3b6e40304d0edcf68466ce686665de45eba39abb"
metafile = true

[[files]]
file = "mods/cat-loaf.pw.toml"
hash = "44e847cebc9cc7f33d4963e134dc2a6b56328c5f8042c24ad9401d1a908ccf09"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "7154671eaa5779417a9a0c3a89e664972f44a513829abb2bd66c0a337dd42548"
metafile = true

[[files]]
file = "mods/cerbons-better-beacons.pw.toml"
hash = "f9a4ca75689069a8d794c71fcccda7e5fc4512311d05d864168b833150aff83f"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "24828835695c3e91f506dab3bdd47e54cb31412187ab0670bbb09cfeb710994c"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "8f534cf725f8fc338c29453a25bbff94c5adba4f4b1815863f5d0f073b8f42e3"
metafile = true

[[files]]
file = "mods/clean-tooltips.pw.toml"
hash = "8c5a282eac619cac210348e162a987f8c45c8a05dd4aebfc6ac35472561ee362"
metafile = true

[[files]]
file = "mods/clear-void.pw.toml"
hash = "fd1923a8b5908be4d6dc5eda6d46e92b5c251f0f98990881c50cde243d33db49"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "ec00fdd4f05b8eb824821f4ee77e3a7112d495e7494d90c95fa2b1388a421e1d"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "0e237a9d698dd3d738c37cc6f85f50f5cb62b9ce05f6546c85b18a4f555c697a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/comfortable-campfires.pw.toml"
hash = "db5e3847a52ce76e3d31ff529f891ba10fb0b778e0c66ac263042ec3dfeee68d"
metafile = true

[[files]]
file = "mods/connected-doors.pw.toml"
hash = "1d912783e5a27dfd863ee3228ca0f907631b7ff30c0ea6fc4764968ca1e3341a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "e7b5d1e23878b9e5b0f2229b6cf9d900c9522a79b3ffe8bcc0e1e1e51df4ba57"
metafile = true

[[files]]
file = "mods/default-components.pw.toml"
hash = "20795f79d092b72b73b68594eff4fc8ad49dfcb9a67dcb9506304f03c585eaa7"
metafile = true

[[files]]
file = "mods/dyed-bundles.pw.toml"
hash = "6c23ab056a68af420b7262d2fd27a57f81f33b373fb85fa0da08f371aa240611"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "a52ba05fa9ffc50b308707fb270b804a91f93377f075065d0f9eeb08a448e844"
metafile = true

[[files]]
file = "mods/dynamiccrosshaircompat.pw.toml"
hash = "6b73f852aa4e6207c63fc360fda524df9f307ba88ba194cae323cdb86824bda6"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "8d0bde383406174b9d427916a20d538c33afd06c09f22b8a6f96830ebecfe227"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
hash = "2a421f249e7022255938fafdebf4a9d6490d62aecbabd48a9e9a3e52aacd4d0b"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "7a488f0a685a3c77e90bb8ab013ffa9d92cc7a895925d8f8629d355ab6b8c07c"
metafile = true

[[files]]
file = "mods/enchiridion.pw.toml"
hash = "84cef0cc404ab0c736b480a3d26c8f73c449129db6293ae4c72b2498d2a2ae13"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6e046a0ced37b978d8bf74aa48653822489348c2e65d33e40b93be55763c983f"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "d41804aff0c09612645047b2e53bfd88a018deaa7e4ad17d6656dd67e0af2a83"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "7aefbabe7adc27461b53e587ca095a3435b32f4d87a1797692655f6b08f0d296"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "b9971aa45df874975e051c11291b040e0f325e3d36c4ee6e93f252fdf7c0ffc3"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "116bec96a1778d1e25963fcbeb4d6110c571cbc09b5413d805e8e34daa2cc0cb"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9ee84bdf71ae7963fabc99e8bb44acb72334d281b02ddac913e25daf7b81c143"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
hash = "8bef8d23da6d792dc203c08face506976f0f4d8666e7c0a32e1386c61659ff1f"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "2467c6382fe14f9e16195d4ebd88b6570d42b2f18f0f28d3a1c8618e5176b7de"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "583db02f6a60be2321bec8293490ba37fc2fe2ddc7664ea2ce57cc28e2fadc74"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "da756fc8e9d124170b0ddfb68815335de72832f6ff973f7798765615bc867fab"
metafile = true

[[files]]
file = "mods/fast-item-frames.pw.toml"
hash = "fa51511255ffa11524e3f2b54d9ff2ba508b8b6de41a62867fe6133030e71a23"
metafile = true

[[files]]
file = "mods/fast-paintings.pw.toml"
hash = "ad92549045da15a3558974bc0729e8c0efb2441fb109f75030e48d7715196d73"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "355b7fb76404011b31ccd2a2417da3e608837a70724823973e32a2179a376cd9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "f9d89c62265e675839395d925f4162e3e93fda837ed50fbe3832f4ae9c58bebb"
metafile = true

[[files]]
file = "mods/horsebuff.pw.toml"
hash = "8e380cf36fbc47843330009c395dc8992baa0da8a79c5d7edbf227d1947377f0"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "858f7eef766bcdc4bb91a0cb82938375a421372c7cdc198f67d1f2254b70eeb5"
metafile = true

[[files]]
file = "mods/item-descriptions.pw.toml"
hash = "f50eeca79dcf567d621ec86967b62c2ae736fefe32d4e4a8120e07706c57e083"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
hash = "d7bc8e3eddeaedd18d4c75061d211196d357fba3f408b3c752cfb68551cad5a7"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "bba6f62c0dc4366620bf0f93081e8b81bcd77b29653faa710c961e53a88d1301"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "34d75daff8b8260780d97bbc2dc545739399df1d5ac304eeb2f80e23354cf3af"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "b41a9d602a2885f672ef02b1426b4d65c17fd34229f40ab265d16e8b5ebc6894"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
hash = "24c60676a7e047654fe15de6ad4ce2c8f90371f86ff39ae470c00250214ca341"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "2e26dd4ebd07b97d68a9775b84fae707d8824c926e086bb3bcad11687b3fb204"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "414c2909a26ebe54725b45866031806212d9c84bff0f1e052ad5f2e5a61d7d53"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d12b136e07f6f83a1e199aabe430426d19702c9f69e55731092b5d5c2f3fb69f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6be9bf8af4c867d6cc7c680df870e2b878fbec4090160f3df3a8426c61216472"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "271ffabbb7e1bde473eb7a9743398fedae4fea4145c8ed0bf60ece7a6e35d0e0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "79a034d9dc8a2cb62a9fcd64c2871e081291a264822da07675a3ee749b04b6eb"
metafile = true

[[files]]
file = "mods/my-nethers-delight-refabricated.pw.toml"
hash = "fea3c7b0d03ac4eeaf70802158faae156f640dec2b66b1ab9e5527ba19a1150e"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "93c5b81a82fffca423eaae73c4ebd729b8d644aad0e35eda39c287f9778fc9a3"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
hash = "e911bf4d0ecaae8377f92a30fe60717579fb132c91db9465073b48c4d30f4104"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "0b35eacc51808809894ef78b91dfd614e056a34708e4bd2aa6f5ebeb7993a1c0"
metafile = true

[[files]]
file = "mods/nostalgic-tweaks.pw.toml"
hash = "ee92e804c6ffd6509e621421b9906efa0f654885053b1ea00c7e4a4eb55dae17"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "a6e3ca19c98f18fcf6e8a89587c0fb15df4a2147db9ae1f18d3d2b178fce10ac"
metafile = true

[[files]]
file = "mods/oxide.pw.toml"
hash = "d439ac7719f6e7ab887b482fcb6005e2f1233cafbc16ab87f4b9b09c64ed2ad0"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "1d99b790a93724f4385696073e03e1437865f63551b86ef7faed493a0ba5c4c8"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "fb8c82bd41ae3eccb939cc7dae2d805171d7575ccfc6788591e96ab4097655a0"
metafile = true

[[files]]
file = "mods/pyrite.pw.toml"
hash = "1abd095c85ceac3cc328ecc5ac181dabed125052c0d3a5a078a0702c4f69f968"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "98362357cbb70b039275c055bb357fad1bb8a1566d5713dd7cfd9132dd606886"
metafile = true

[[files]]
file = "mods/rapscallions-and-rockhoppers.pw.toml"
hash = "7643a0442e6b5fdcc52fb06c9e7f4958dd46570a6a3ddad3b6b01b39ec5125fe"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/rounded_mod.pw.toml"
hash = "976bfd8d4cdd96995adf4fd60659eabfcecee721c83c11119ad5287d0d1ed2d2"
metafile = true

[[files]]
file = "mods/scholar.pw.toml"
hash = "e5f87e1e6fe6f42c25ccaf88d935e231b9c0aedce9795dc98e7a218b9af6de40"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "86ff9b67d90f046045619aa571df7bad909e480711c5d8b8967e3efca84ad16a"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
hash = "072d663edf6434788b126994b7901a654efb279c4b7f503bcad4938d6d6396a5"
metafile = true

[[files]]
file = "mods/sleep-warp-updated.pw.toml"
hash = "065a6c92f489bce0ef6b27f0b05acde22920c5f5f15414171890ec5ea375fe16"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2c242048726e82d36863b81ecbaa342328bb2929dc82da2f573d83b9f0711505"
metafile = true

[[files]]
file = "mods/spyglass-improvements.pw.toml"
hash = "7c5720177f0c9eae683d8c06455c922a50a01ae4e868c4c78ec3d430e67231ad"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "552e4b6238d140decb9d75e938541d707636519b38eff445b65cbb63590d5c75"
metafile = true

[[files]]
file = "mods/templates-2.pw.toml"
hash = "55de3aa867841af02dc02b83983de55917f99237a6def88736bb556903aad5ad"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "e35593590fe988653baebae4638f6c93b5d822351274955cc1288b34fe5429fe"
metafile = true

[[files]]
file = "mods/tinkerers-smithing.pw.toml"
hash = "7e80608eb4d7abb46a4c9ee5d193805caddec1afaf2da22ca227be990878f97d"
metafile = true

[[files]]
file = "mods/useful-spyglass.pw.toml"
hash = "2bc3e01251efff5c25c7f54d8f02ca7a9e6249511c06999df322a3b8a118bd09"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "39426bfeeab22ea17f94fd3904dd9b78f9a3c9b4ddcb732b734ddbfd0e3568af"
metafile = true

[[files]]
file = "mods/weird-wares.pw.toml"
hash = "6b9dca97f63507a9e5513f66bc7aed91cf27731066ff64090c9463610df2af4a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "052b70117c2e9a3a697a36f449b220be7bfba215f3a2e43b5ce7faff9e88b2e6"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "19bfaf808255bb6a5508cb2c861779c433a5ed58e7889755938dc12cb479e912"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "ffcf32caf3dda8f05adb109dc86c477cf1bb768bac6232bc5bcf0d60a7861bcb"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "1bd0ba1128e6ae3f926298c2ffe33180cca75362fae3bd92146d43977297f01c"
metafile = true

[[files]]
file = "resources/common/required/LemonSorbet/assets/minecraft/lang/en_us.json"
hash = "aaec6cc53e815b236971297f71c649755c1b1ce6134b9c7d14bd47023808a78a"

[[files]]
file = "resources/common/required/LemonSorbet/assets/minecraft/models/block/ancient_debris.json"
hash = "9ea6cffe9bbddf3a5ecd13c7684001835a2838b18f0e54a03081eb8aee4ea54c"

[[files]]
file = "resources/common/required/LemonSorbet/assets/minecraft/textures/block/ancient_debris_side.png"
hash = "8bb12d0287ae41508bc1da9e573e9852e2c2583b9ddc61c4d64aabc9a9cb44ea"

[[files]]
file = "resources/common/required/LemonSorbet/assets/minecraft/textures/block/ancient_debris_top.png"
hash = "123e91c6586220d921c4d81b9308be743ec006b3dfc6756cbb0c660fbdd7afec"

[[files]]
file = "resources/common/required/LemonSorbet/assets/minecraft/textures/block/end_stone.png"
hash = "a34eba1313eb84b54547000cf48312b13def8c8fa41637abc211c252b0aeaec4"

[[files]]
file = "resources/common/required/LemonSorbet/pack.mcmeta"
hash = "f0a21315b604245630257e1464135554e1cf1e2c5ab6ea854b1b57008f98327d"

[[files]]
file = "resources/common/required/VanillaTweaks_r903271_MC1.21.x.zip"
hash = "b4f9bb3d4063170941f2e969785c661e1e8c0bc6bbcd1dd7b96c6959915634c8"

[[files]]
file = "resources/common/required/coolfont.pw.toml"
hash = "2adffdf6bacc2d4c50c955d46becd3cc21c019f85f958af42577d4ccad671031"
metafile = true

[[files]]
file = "resources/common/required/javaui.pw.toml"
hash = "e8ead33563ef7139ad57a80479bc556d587b8e8b6bd92511c2b0b9e4863bac60"
metafile = true

[[files]]
file = "resources/common/required/mod-descriptions.pw.toml"
hash = "91d1bac89a84d51adc8bdd51b1076bf1acda10948d7a566cc7e02805deee3c3b"
metafile = true

[[files]]
file = "resources/common/required/peeves.pw.toml"
hash = "6230bc3576d6281c16e202180c92c143f4d7981f5290c92c014802ccf13f41a1"
metafile = true

[[files]]
file = "resources/common/required/quark-vro.pw.toml"
hash = "840977878aa78d7c52be23ec42bf07fc014ef72795c1290a04443cb0fc4197ab"
metafile = true
