hash-format = "sha256"

[[files]]
file = ".nojekyll"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "mods/amendments.pw.toml"
hash = "71385a965a8391b709fc68784d7c7933eb837048cf0649d3a20a065258fe3e8c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "bdaedb87300594cb776756286d7f615cba17a460e2b1e63de9f6881f44cb277e"
metafile = true

[[files]]
file = "mods/bovines-and-buttercups.pw.toml"
hash = "39fff4a3d88f6a36494f8453cf4586325e340322765e4c3cd8f8ed0066b1a0ee"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "8f6036f3067befffc33b106df2e56fc076deaeffecf079957c46c6c00def2ed1"
metafile = true

[[files]]
file = "mods/bundled_.pw.toml"
hash = "0ab032a5ecd0385858fe53ea3b6e40304d0edcf68466ce686665de45eba39abb"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "ec00fdd4f05b8eb824821f4ee77e3a7112d495e7494d90c95fa2b1388a421e1d"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "0e237a9d698dd3d738c37cc6f85f50f5cb62b9ce05f6546c85b18a4f555c697a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "e7b5d1e23878b9e5b0f2229b6cf9d900c9522a79b3ffe8bcc0e1e1e51df4ba57"
metafile = true

[[files]]
file = "mods/default-components.pw.toml"
hash = "20795f79d092b72b73b68594eff4fc8ad49dfcb9a67dcb9506304f03c585eaa7"
metafile = true

[[files]]
file = "mods/dyed-bundles.pw.toml"
hash = "6c23ab056a68af420b7262d2fd27a57f81f33b373fb85fa0da08f371aa240611"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "8d0bde383406174b9d427916a20d538c33afd06c09f22b8a6f96830ebecfe227"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
hash = "2a421f249e7022255938fafdebf4a9d6490d62aecbabd48a9e9a3e52aacd4d0b"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "6a5503f90eda6b64b4eb121e3b2fb40d33ec8a97abae5dc9db49d37d45200ccf"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "39225a351af4cac54235997cc04af74a358bf6a5fa1a9c78d7af47d5c74903ce"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6e046a0ced37b978d8bf74aa48653822489348c2e65d33e40b93be55763c983f"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "d41804aff0c09612645047b2e53bfd88a018deaa7e4ad17d6656dd67e0af2a83"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "b9971aa45df874975e051c11291b040e0f325e3d36c4ee6e93f252fdf7c0ffc3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "a19f6561d4d952aaf56c494326f4c59b0f276ab2f42f119e99ffb6fb62e7e7c9"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "2467c6382fe14f9e16195d4ebd88b6570d42b2f18f0f28d3a1c8618e5176b7de"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "da756fc8e9d124170b0ddfb68815335de72832f6ff973f7798765615bc867fab"
metafile = true

[[files]]
file = "mods/fast-item-frames.pw.toml"
hash = "d3846737bd90c652cb8d25192ba5c83e5e869028ee34e2f992b2bca9842bcfb5"
metafile = true

[[files]]
file = "mods/fast-paintings.pw.toml"
hash = "ad92549045da15a3558974bc0729e8c0efb2441fb109f75030e48d7715196d73"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "355b7fb76404011b31ccd2a2417da3e608837a70724823973e32a2179a376cd9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "f9d89c62265e675839395d925f4162e3e93fda837ed50fbe3832f4ae9c58bebb"
metafile = true

[[files]]
file = "mods/horsebuff.pw.toml"
hash = "8e380cf36fbc47843330009c395dc8992baa0da8a79c5d7edbf227d1947377f0"
metafile = true

[[files]]
file = "mods/item-descriptions.pw.toml"
hash = "b230b2aa21460cf024046f3c6b71a92a1128309c997c3721a0622289e3a0d246"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "bba6f62c0dc4366620bf0f93081e8b81bcd77b29653faa710c961e53a88d1301"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6be9bf8af4c867d6cc7c680df870e2b878fbec4090160f3df3a8426c61216472"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "271ffabbb7e1bde473eb7a9743398fedae4fea4145c8ed0bf60ece7a6e35d0e0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "79a034d9dc8a2cb62a9fcd64c2871e081291a264822da07675a3ee749b04b6eb"
metafile = true

[[files]]
file = "mods/my-nethers-delight-refabricated.pw.toml"
hash = "fea3c7b0d03ac4eeaf70802158faae156f640dec2b66b1ab9e5527ba19a1150e"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "93c5b81a82fffca423eaae73c4ebd729b8d644aad0e35eda39c287f9778fc9a3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "0b35eacc51808809894ef78b91dfd614e056a34708e4bd2aa6f5ebeb7993a1c0"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "42e99ea03a01f933a334dfdfb6babbdcc5d9b38c076e4d3c821a96a9730318b7"
metafile = true

[[files]]
file = "mods/oxide.pw.toml"
hash = "d439ac7719f6e7ab887b482fcb6005e2f1233cafbc16ab87f4b9b09c64ed2ad0"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "fb8c82bd41ae3eccb939cc7dae2d805171d7575ccfc6788591e96ab4097655a0"
metafile = true

[[files]]
file = "mods/pyrite.pw.toml"
hash = "1abd095c85ceac3cc328ecc5ac181dabed125052c0d3a5a078a0702c4f69f968"
metafile = true

[[files]]
file = "mods/rapscallions-and-rockhoppers.pw.toml"
hash = "f907f068c17a14ed621b1680a2f67dffc76db806643666894170fad407e37604"
metafile = true

[[files]]
file = "mods/rounded_mod.pw.toml"
hash = "976bfd8d4cdd96995adf4fd60659eabfcecee721c83c11119ad5287d0d1ed2d2"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
hash = "072d663edf6434788b126994b7901a654efb279c4b7f503bcad4938d6d6396a5"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "552e4b6238d140decb9d75e938541d707636519b38eff445b65cbb63590d5c75"
metafile = true

[[files]]
file = "mods/templates-2.pw.toml"
hash = "a882e54ca7d302b95b7e789afd46c1c8eeaadf43590727b829e1f41885af26b5"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "e35593590fe988653baebae4638f6c93b5d822351274955cc1288b34fe5429fe"
metafile = true

[[files]]
file = "mods/tinkerers-smithing.pw.toml"
hash = "7e80608eb4d7abb46a4c9ee5d193805caddec1afaf2da22ca227be990878f97d"
metafile = true

[[files]]
file = "mods/useful-spyglass.pw.toml"
hash = "2bc3e01251efff5c25c7f54d8f02ca7a9e6249511c06999df322a3b8a118bd09"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "052b70117c2e9a3a697a36f449b220be7bfba215f3a2e43b5ce7faff9e88b2e6"
metafile = true

[[files]]
file = "resources/common/required/VanillaTweaks_r903271_MC1.21.x.zip"
hash = "b4f9bb3d4063170941f2e969785c661e1e8c0bc6bbcd1dd7b96c6959915634c8"

[[files]]
file = "resources/common/required/javaui.pw.toml"
hash = "e8ead33563ef7139ad57a80479bc556d587b8e8b6bd92511c2b0b9e4863bac60"
metafile = true

[[files]]
file = "resources/common/required/peeves.pw.toml"
hash = "6230bc3576d6281c16e202180c92c143f4d7981f5290c92c014802ccf13f41a1"
metafile = true
