hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b21ef031c6ad139361352529cb63f4799ffa91008895e1c7a9a5102ea007ae2d"
metafile = true

[[files]]
file = "mods/bibliocraft-legacy.pw.toml"
hash = "814bb63792157879e54a622692f63245e8349a41ef39d93957acf3999ac259b3"
metafile = true

[[files]]
file = "mods/bovines-and-buttercups.pw.toml"
hash = "4b7bd05a251f135b2cf63b6e4eaf14ce8af5d12c52fcad4d8f1b1fd79428fc70"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "4fa442ceef3813ea27ecdf07f9129d31ec9fcd6b85c971020144482e6c9b1c95"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "ffb0861ae37abc292e61208c8b7826b7b8287b24c07419083d4bb4ac109da4ee"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "0a4d0034c5a1379d5aa57c0a104aaa2adbb98f1e2b89d4ec0b7ef68df2e16a1a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "a4c8371232d9f542b180c7bd7e30d84b9e958b97b24af5dde0759ab8e511fb8e"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
hash = "109c9d01f242faad432dc1cfc03a0fd0dcfe5623c28cbe2bc9092ec01dec6ec8"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "778c42263b2ba7c9e73553bdcd70f48a3e485ba52b6a83474160d48be696b71f"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f98bb58144f3b207bc5ebc99d898e1c2557924e27f403e670f491f5ec7d72863"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "e5125f8f2709fd20f8182fade3d7f9e7129872c63f042c5489c6eba4733b6b49"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "867a029a8bed75bea2fb02e5186730db46ec01f970d0bdb266c6897074c16177"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "d6f2fdcf0f4bc67dccd8e036f7c8117ffd76a008bd50e2a060cd23671ef9abb9"
metafile = true

[[files]]
file = "mods/item-descriptions.pw.toml"
hash = "b902e2a8d9a070dec6136632ea901f2bcb7185c41554d08128f377a1825ed495"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "77b86ca843207273549875640b1c16254c2486e67127c37344c186b503da96ed"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "734da85a1770ed0489132d97ce86130c5dc1ae1800d5802d5ecb07f44e15468b"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "d79c6acf7b4646175124345daae6f3fd000e362bb89724e5b8ed1b5b1e18b6f1"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "b3e831b3e4d6ddbf23806b0fec6087eca264af1ebc04e747c89024972aaa8607"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "35ecf5a8ecf2d7b1a2b79f5d24a093e21d23f12486dcd71689894758d2fbe832"
metafile = true

[[files]]
file = "mods/pyrite.pw.toml"
hash = "7678b81515c9403fe29d98e3b9f9570e2addb4aedd235918e0bdf60657f5e0c0"
metafile = true

[[files]]
file = "mods/rapscallions-and-rockhoppers.pw.toml"
hash = "f8ea70dce766d9882628c103dc75a11db5f05c4bff719a0cd813ef101106ceb5"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "17ffede678924aa27782eb98ea984220e3973f2b78d581b417b8471f1a3168b0"
metafile = true

[[files]]
file = "mods/useful-spyglass.pw.toml"
hash = "1a9b7b2207aa66f6a6dd6a19d3fca9900715e39428ef8f5210875f006b55f97a"
metafile = true
