name = "Lemon Sorbet"
author = "cassiancc"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "673b09ff509e7714655e355bf4c75ff0097736d055c7ff15e0f5bdc34d33dd95"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
