name = "Lemon Sorbet"
author = "cassiancc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f9b4ddf0ba3de3f956a773df7a38e2821138f5978fe2d4087bb4b3295b9ac10"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
