name = "Lemon Sorbet"
author = "cassiancc"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0351538574ba85e22c95402ed26a506f2941ba73fe1d06545d7cb4bff172447d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
