name = "Lemon Sorbet"
author = "cassiancc"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63d4f7cfd44050d18c3da15544d3ca6aba8896f9bbf5be985ccc17c199a0d4d4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
