name = "Lemon Sorbet"
author = "cassiancc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3836c06b243927224e9a6b874be79eac1ae689ba366cdb9d3495e3ef41ae60d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.138"
