name = "Lemon Sorbet"
author = "cassiancc"
version = "0.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5a0dd86dd364584743bb143e8af193afafb73e98c44015d18b907e47c704832"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
