name = "Lemon Sorbet"
author = "cassiancc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7746805a4eedd6a6b95299c464fb3f513b07982d375bbb85bd0635ec0772b24d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
