# Whether to wrap around to the beginning after scrolling past the end of the list
# default: true
wrap_scrolling = true
# If the shape switcher menu should be scrolling or static
# default: true
scrolling = true
# If the change block shape key should be held or toggled to open the menu
# options: hold, toggle, press
# default: hold
hold = "HOLD"
# Whether to generate a resource pack for vertical slabs and steps when the game is launched.
# default: true
runtime_asset_generation = false
